feat: ignore pack if no static.json is found

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -4,8 +4,8 @@
 build_dir=$1
 
 if [ ! -f "$build_dir/static.json" ]; then
-    echo "Could not find 'static.json'! Please ensure it exists and is checked into Git." >&2
-    exit 1
+    echo "Could not find 'static.json'! So we do nothing with this build pack." >&2
+    exit 0
 fi
 
 echo 'Static HTML'
